### PR TITLE
Add small icon for notification update

### PR DESCRIPTION
**Pull request by khrizt**
Hi,

As I told you in issue [#8](https://github.com/javiersantos/AppUpdater/issues/8) I'd like to have my own custom icon in notification, I made a commit to achieve that. I don't know if that's how you wanted, if you prefer other way I can change it.

Thanks

### CODE REVIEW

**Comment by javiersantos** [comment]
Awesome! Nice work :+1:

**Comment by khrizt** [comment]
Thanks man! Will you do a release for this?

**Comment by javiersantos** [comment]
I've just updated the library. Thanks.
```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:1.2.2'
}
```

**Comment by khrizt** [comment]
Soooo great! Thanks Javier

**Pull request merged**
